//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkerScreen.resources.Langs {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("WorkerScreen.resources.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string emergency {
            get {
                return ResourceManager.GetString("emergency", resourceCulture);
            }
        }
        
        internal static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        internal static string signIn {
            get {
                return ResourceManager.GetString("signIn", resourceCulture);
            }
        }
        
        internal static string signInAgain {
            get {
                return ResourceManager.GetString("signInAgain", resourceCulture);
            }
        }
        
        internal static string signInText {
            get {
                return ResourceManager.GetString("signInText", resourceCulture);
            }
        }
        
        internal static string signInEmergencyText {
            get {
                return ResourceManager.GetString("signInEmergencyText", resourceCulture);
            }
        }
        
        internal static string offLine {
            get {
                return ResourceManager.GetString("offLine", resourceCulture);
            }
        }
        
        internal static string entranceApprove {
            get {
                return ResourceManager.GetString("entranceApprove", resourceCulture);
            }
        }
        
        internal static string entranceRequest {
            get {
                return ResourceManager.GetString("entranceRequest", resourceCulture);
            }
        }
        
        internal static string _lock {
            get {
                return ResourceManager.GetString("lock", resourceCulture);
            }
        }
        
        internal static string offLineSettings {
            get {
                return ResourceManager.GetString("offLineSettings", resourceCulture);
            }
        }
        
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        internal static string areaManagement {
            get {
                return ResourceManager.GetString("areaManagement", resourceCulture);
            }
        }
        
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        internal static string area {
            get {
                return ResourceManager.GetString("area", resourceCulture);
            }
        }
        
        internal static string enter {
            get {
                return ResourceManager.GetString("enter", resourceCulture);
            }
        }
        
        internal static string signOut {
            get {
                return ResourceManager.GetString("signOut", resourceCulture);
            }
        }
        
        internal static string offLineRe {
            get {
                return ResourceManager.GetString("offLineRe", resourceCulture);
            }
        }
        
        internal static string offLineSetting {
            get {
                return ResourceManager.GetString("offLineSetting", resourceCulture);
            }
        }
        
        internal static string offLineSync {
            get {
                return ResourceManager.GetString("offLineSync", resourceCulture);
            }
        }
        
        internal static string offLineSyncInfo {
            get {
                return ResourceManager.GetString("offLineSyncInfo", resourceCulture);
            }
        }
        
        internal static string region {
            get {
                return ResourceManager.GetString("region", resourceCulture);
            }
        }
        
        internal static string approver {
            get {
                return ResourceManager.GetString("approver", resourceCulture);
            }
        }
        
        internal static string entranceDate {
            get {
                return ResourceManager.GetString("entranceDate", resourceCulture);
            }
        }
        
        internal static string entranceWhy {
            get {
                return ResourceManager.GetString("entranceWhy", resourceCulture);
            }
        }
        
        internal static string level {
            get {
                return ResourceManager.GetString("level", resourceCulture);
            }
        }
        
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        internal static string request {
            get {
                return ResourceManager.GetString("request", resourceCulture);
            }
        }
        
        internal static string team {
            get {
                return ResourceManager.GetString("team", resourceCulture);
            }
        }
        
        internal static string approverHelp {
            get {
                return ResourceManager.GetString("approverHelp", resourceCulture);
            }
        }
        
        internal static string areaHelp {
            get {
                return ResourceManager.GetString("areaHelp", resourceCulture);
            }
        }
        
        internal static string entranceDateHelp {
            get {
                return ResourceManager.GetString("entranceDateHelp", resourceCulture);
            }
        }
        
        internal static string entranceReasonHelp {
            get {
                return ResourceManager.GetString("entranceReasonHelp", resourceCulture);
            }
        }
        
        internal static string levelHelp {
            get {
                return ResourceManager.GetString("levelHelp", resourceCulture);
            }
        }
        
        internal static string lockHelp {
            get {
                return ResourceManager.GetString("lockHelp", resourceCulture);
            }
        }
        
        internal static string searchHelp {
            get {
                return ResourceManager.GetString("searchHelp", resourceCulture);
            }
        }
        
        internal static string successHelp {
            get {
                return ResourceManager.GetString("successHelp", resourceCulture);
            }
        }
        
        internal static string requestDo {
            get {
                return ResourceManager.GetString("requestDo", resourceCulture);
            }
        }
        
        internal static string requestList {
            get {
                return ResourceManager.GetString("requestList", resourceCulture);
            }
        }
        
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        internal static string msg_offLineInfo {
            get {
                return ResourceManager.GetString("msg_offLineInfo", resourceCulture);
            }
        }
        
        internal static string msg_signOut {
            get {
                return ResourceManager.GetString("msg_signOut", resourceCulture);
            }
        }
        
        internal static string offLineText {
            get {
                return ResourceManager.GetString("offLineText", resourceCulture);
            }
        }
        
        internal static string darkMode {
            get {
                return ResourceManager.GetString("darkMode", resourceCulture);
            }
        }
        
        internal static string modify {
            get {
                return ResourceManager.GetString("modify", resourceCulture);
            }
        }
        
        internal static string msg_noNetwrok {
            get {
                return ResourceManager.GetString("msg_noNetwrok", resourceCulture);
            }
        }
        
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        internal static string query_UserCheck {
            get {
                return ResourceManager.GetString("query_UserCheck", resourceCulture);
            }
        }
        
        internal static string msg_checkID {
            get {
                return ResourceManager.GetString("msg_checkID", resourceCulture);
            }
        }
        
        internal static string signInUnknownText {
            get {
                return ResourceManager.GetString("signInUnknownText", resourceCulture);
            }
        }
        
        internal static string systemError {
            get {
                return ResourceManager.GetString("systemError", resourceCulture);
            }
        }
        
        internal static string query_GetCodeMaster {
            get {
                return ResourceManager.GetString("query_GetCodeMaster", resourceCulture);
            }
        }
        
        internal static string query_GetAreas {
            get {
                return ResourceManager.GetString("query_GetAreas", resourceCulture);
            }
        }
        
        internal static string query_GetEmployees {
            get {
                return ResourceManager.GetString("query_GetEmployees", resourceCulture);
            }
        }
        
        internal static string approvalDone {
            get {
                return ResourceManager.GetString("approvalDone", resourceCulture);
            }
        }
        
        internal static string msg_fillRequest {
            get {
                return ResourceManager.GetString("msg_fillRequest", resourceCulture);
            }
        }
        
        internal static string query_SearchRequests {
            get {
                return ResourceManager.GetString("query_SearchRequests", resourceCulture);
            }
        }
        
        internal static string query_SetRequest {
            get {
                return ResourceManager.GetString("query_SetRequest", resourceCulture);
            }
        }
        
        internal static string requesting {
            get {
                return ResourceManager.GetString("requesting", resourceCulture);
            }
        }
        
        internal static string msg_alreadyExist {
            get {
                return ResourceManager.GetString("msg_alreadyExist", resourceCulture);
            }
        }
        
        internal static string msg_alreadyPass {
            get {
                return ResourceManager.GetString("msg_alreadyPass", resourceCulture);
            }
        }
        
        internal static string msg_deleteRequest {
            get {
                return ResourceManager.GetString("msg_deleteRequest", resourceCulture);
            }
        }
        
        internal static string noData {
            get {
                return ResourceManager.GetString("noData", resourceCulture);
            }
        }
        
        internal static string query_RequestCheck {
            get {
                return ResourceManager.GetString("query_RequestCheck", resourceCulture);
            }
        }
        
        internal static string query_SearchLocks {
            get {
                return ResourceManager.GetString("query_SearchLocks", resourceCulture);
            }
        }
        
        internal static string allSelectText {
            get {
                return ResourceManager.GetString("allSelectText", resourceCulture);
            }
        }
        
        internal static string approval {
            get {
                return ResourceManager.GetString("approval", resourceCulture);
            }
        }
        
        internal static string approvalCancel {
            get {
                return ResourceManager.GetString("approvalCancel", resourceCulture);
            }
        }
        
        internal static string msg_approvalInfo {
            get {
                return ResourceManager.GetString("msg_approvalInfo", resourceCulture);
            }
        }
        
        internal static string msg_approve {
            get {
                return ResourceManager.GetString("msg_approve", resourceCulture);
            }
        }
        
        internal static string msg_cancelRequest {
            get {
                return ResourceManager.GetString("msg_cancelRequest", resourceCulture);
            }
        }
        
        internal static string msg_selectRequest {
            get {
                return ResourceManager.GetString("msg_selectRequest", resourceCulture);
            }
        }
        
        internal static string msg_lock {
            get {
                return ResourceManager.GetString("msg_lock", resourceCulture);
            }
        }
        
        internal static string msg_successApprove {
            get {
                return ResourceManager.GetString("msg_successApprove", resourceCulture);
            }
        }
        
        internal static string msg_successSync {
            get {
                return ResourceManager.GetString("msg_successSync", resourceCulture);
            }
        }
        
        internal static string no_sync {
            get {
                return ResourceManager.GetString("no_sync", resourceCulture);
            }
        }
        
        internal static string msg_goToMain {
            get {
                return ResourceManager.GetString("msg_goToMain", resourceCulture);
            }
        }
        
        internal static string noOpenData {
            get {
                return ResourceManager.GetString("noOpenData", resourceCulture);
            }
        }
        
        internal static string msg_afterSetup {
            get {
                return ResourceManager.GetString("msg_afterSetup", resourceCulture);
            }
        }
        
        internal static string msg_noClickRequest {
            get {
                return ResourceManager.GetString("msg_noClickRequest", resourceCulture);
            }
        }
        
        internal static string msg_syncing {
            get {
                return ResourceManager.GetString("msg_syncing", resourceCulture);
            }
        }
        
        internal static string msg_syncMaster {
            get {
                return ResourceManager.GetString("msg_syncMaster", resourceCulture);
            }
        }
        
        internal static string snSearch {
            get {
                return ResourceManager.GetString("snSearch", resourceCulture);
            }
        }
        
        internal static string noLockData {
            get {
                return ResourceManager.GetString("noLockData", resourceCulture);
            }
        }
        
        internal static string msg_getLockInfo {
            get {
                return ResourceManager.GetString("msg_getLockInfo", resourceCulture);
            }
        }
        
        internal static string noResult {
            get {
                return ResourceManager.GetString("noResult", resourceCulture);
            }
        }
        
        internal static string msg_locked {
            get {
                return ResourceManager.GetString("msg_locked", resourceCulture);
            }
        }
        
        internal static string msg_plsSync {
            get {
                return ResourceManager.GetString("msg_plsSync", resourceCulture);
            }
        }
        
        internal static string msg_sendLog {
            get {
                return ResourceManager.GetString("msg_sendLog", resourceCulture);
            }
        }
        
        internal static string msg_unlocked {
            get {
                return ResourceManager.GetString("msg_unlocked", resourceCulture);
            }
        }
        
        internal static string msg_noOffLineKey {
            get {
                return ResourceManager.GetString("msg_noOffLineKey", resourceCulture);
            }
        }
        
        internal static string defaultPwd {
            get {
                return ResourceManager.GetString("defaultPwd", resourceCulture);
            }
        }
        
        internal static string msg_areaMoreThanOne {
            get {
                return ResourceManager.GetString("msg_areaMoreThanOne", resourceCulture);
            }
        }
        
        internal static string msg_noLocalUser {
            get {
                return ResourceManager.GetString("msg_noLocalUser", resourceCulture);
            }
        }
        
        internal static string msg_notMatchPwd {
            get {
                return ResourceManager.GetString("msg_notMatchPwd", resourceCulture);
            }
        }
        
        internal static string msg_notNumPwd {
            get {
                return ResourceManager.GetString("msg_notNumPwd", resourceCulture);
            }
        }
        
        internal static string msg_successPwd {
            get {
                return ResourceManager.GetString("msg_successPwd", resourceCulture);
            }
        }
        
        internal static string msg_sendOffLineLog {
            get {
                return ResourceManager.GetString("msg_sendOffLineLog", resourceCulture);
            }
        }
        
        internal static string msg_deleteRecent {
            get {
                return ResourceManager.GetString("msg_deleteRecent", resourceCulture);
            }
        }
        
        internal static string msg_register {
            get {
                return ResourceManager.GetString("msg_register", resourceCulture);
            }
        }
        
        internal static string msg_success {
            get {
                return ResourceManager.GetString("msg_success", resourceCulture);
            }
        }
        
        internal static string msg_sucRegister {
            get {
                return ResourceManager.GetString("msg_sucRegister", resourceCulture);
            }
        }
        
        internal static string msg_verify {
            get {
                return ResourceManager.GetString("msg_verify", resourceCulture);
            }
        }
        
        internal static string msg_verify2 {
            get {
                return ResourceManager.GetString("msg_verify2", resourceCulture);
            }
        }
        
        internal static string msg_errorMac {
            get {
                return ResourceManager.GetString("msg_errorMac", resourceCulture);
            }
        }
        
        internal static string ilsSearch {
            get {
                return ResourceManager.GetString("ilsSearch", resourceCulture);
            }
        }
        
        internal static string msg_noILS {
            get {
                return ResourceManager.GetString("msg_noILS", resourceCulture);
            }
        }
        
        internal static string msg_offLineAsync {
            get {
                return ResourceManager.GetString("msg_offLineAsync", resourceCulture);
            }
        }
        
        internal static string msg_back {
            get {
                return ResourceManager.GetString("msg_back", resourceCulture);
            }
        }
        
        internal static string msg_update {
            get {
                return ResourceManager.GetString("msg_update", resourceCulture);
            }
        }
        
        internal static string msg_requestDate {
            get {
                return ResourceManager.GetString("msg_requestDate", resourceCulture);
            }
        }
        
        internal static string offLineSyncInfoUser {
            get {
                return ResourceManager.GetString("offLineSyncInfoUser", resourceCulture);
            }
        }
        
        internal static string msg_enterlimit {
            get {
                return ResourceManager.GetString("msg_enterlimit", resourceCulture);
            }
        }
        
        internal static string msg_verify3 {
            get {
                return ResourceManager.GetString("msg_verify3", resourceCulture);
            }
        }
        
        internal static string msg_outArange {
            get {
                return ResourceManager.GetString("msg_outArange", resourceCulture);
            }
        }
        
        internal static string msg_saved {
            get {
                return ResourceManager.GetString("msg_saved", resourceCulture);
            }
        }
        
        internal static string msg_commandReceive {
            get {
                return ResourceManager.GetString("msg_commandReceive", resourceCulture);
            }
        }
        
        internal static string msg_errorRetry {
            get {
                return ResourceManager.GetString("msg_errorRetry", resourceCulture);
            }
        }
        
        internal static string msg_lockClosed {
            get {
                return ResourceManager.GetString("msg_lockClosed", resourceCulture);
            }
        }
        
        internal static string msg_lockConnected {
            get {
                return ResourceManager.GetString("msg_lockConnected", resourceCulture);
            }
        }
        
        internal static string msg_lockConnectionError {
            get {
                return ResourceManager.GetString("msg_lockConnectionError", resourceCulture);
            }
        }
        
        internal static string msg_lockConnectionErrorRetry {
            get {
                return ResourceManager.GetString("msg_lockConnectionErrorRetry", resourceCulture);
            }
        }
        
        internal static string msg_lockDisconnected {
            get {
                return ResourceManager.GetString("msg_lockDisconnected", resourceCulture);
            }
        }
        
        internal static string msg_lockFound {
            get {
                return ResourceManager.GetString("msg_lockFound", resourceCulture);
            }
        }
        
        internal static string msg_lockTouch {
            get {
                return ResourceManager.GetString("msg_lockTouch", resourceCulture);
            }
        }
        
        internal static string msg_offlineKeyNeed {
            get {
                return ResourceManager.GetString("msg_offlineKeyNeed", resourceCulture);
            }
        }
        
        internal static string msg_offlineKeyUse {
            get {
                return ResourceManager.GetString("msg_offlineKeyUse", resourceCulture);
            }
        }
        
        internal static string msg_phoneBluetoothError {
            get {
                return ResourceManager.GetString("msg_phoneBluetoothError", resourceCulture);
            }
        }
        
        internal static string msg_timeoutReconnection {
            get {
                return ResourceManager.GetString("msg_timeoutReconnection", resourceCulture);
            }
        }
        
        internal static string stateLock {
            get {
                return ResourceManager.GetString("stateLock", resourceCulture);
            }
        }
        
        internal static string stateUnlock {
            get {
                return ResourceManager.GetString("stateUnlock", resourceCulture);
            }
        }
        
        internal static string userStop {
            get {
                return ResourceManager.GetString("userStop", resourceCulture);
            }
        }
        
        internal static string approverSearch {
            get {
                return ResourceManager.GetString("approverSearch", resourceCulture);
            }
        }
        
        internal static string msg_open {
            get {
                return ResourceManager.GetString("msg_open", resourceCulture);
            }
        }
        
        internal static string msg_offLineAsyncAll {
            get {
                return ResourceManager.GetString("msg_offLineAsyncAll", resourceCulture);
            }
        }
        
        internal static string msg_offLineAsyncPart {
            get {
                return ResourceManager.GetString("msg_offLineAsyncPart", resourceCulture);
            }
        }
        
        internal static string msg_lockAbnormal {
            get {
                return ResourceManager.GetString("msg_lockAbnormal", resourceCulture);
            }
        }
        
        internal static string msg_lowBatteryWarn {
            get {
                return ResourceManager.GetString("msg_lowBatteryWarn", resourceCulture);
            }
        }
        
        internal static string msg_lowBatteryDanger {
            get {
                return ResourceManager.GetString("msg_lowBatteryDanger", resourceCulture);
            }
        }
        
        internal static string msg_lowBatteryError {
            get {
                return ResourceManager.GetString("msg_lowBatteryError", resourceCulture);
            }
        }
        
        internal static string query_GetLockOfflineKeys {
            get {
                return ResourceManager.GetString("query_GetLockOfflineKeys", resourceCulture);
            }
        }
        
        internal static string msg_mainLockInfo {
            get {
                return ResourceManager.GetString("msg_mainLockInfo", resourceCulture);
            }
        }
        
        internal static string forceLockText {
            get {
                return ResourceManager.GetString("forceLockText", resourceCulture);
            }
        }
        
        internal static string msg_lockListInfo {
            get {
                return ResourceManager.GetString("msg_lockListInfo", resourceCulture);
            }
        }
        
        internal static string msg_timeoutArange {
            get {
                return ResourceManager.GetString("msg_timeoutArange", resourceCulture);
            }
        }
        
        internal static string query_GetLockInfo_limit {
            get {
                return ResourceManager.GetString("query_GetLockInfo_limit", resourceCulture);
            }
        }
        
        internal static string query_GetLockInfo {
            get {
                return ResourceManager.GetString("query_GetLockInfo", resourceCulture);
            }
        }
        
        internal static string query_SearchLocksAllOffline {
            get {
                return ResourceManager.GetString("query_SearchLocksAllOffline", resourceCulture);
            }
        }
        
        internal static string favorite {
            get {
                return ResourceManager.GetString("favorite", resourceCulture);
            }
        }
    }
}
